In [84]:
import pandas as pd

In [85]:
# pip install openpyxl

In [86]:
data = pd.read_excel("Docking_high_low_energy_labels.xlsx")

/home/LuisPabloElChido/miniconda3/envs/qiskit_general/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [87]:
data.head()

,Index,Sequence Epitope),Binding Energy,Otsu Class theshold -77.8,Abs dist to threshold,Unnamed: 5,Unnamed: 6,Receptor_Sequnce for SLA-1 0401
0,1.0,RVPILRTVF,-92.5,Strong,14.7,NaN,NaN,MGPGALFLLLSGTLALTGTQAGPHSLSYFYTAVSRPDRGDSRFIAV...
1,2.0,VPILRTVFG,-77.1,Weak,0.7,NaN,NaN,NaN
2,3.0,RTVFGFRWL,-99.6,Strong,21.8,NaN,NaN,NaN
3,4.0,PTPPQRQAL,-48.5,Weak,29.3,NaN,NaN,NaN
4,5.0,LLSSKTSVA,-50.1,Weak,27.7,NaN,NaN,NaN

In [88]:
data = data.drop(columns=["Index","Unnamed: 5", "Unnamed: 6","Receptor_Sequnce for SLA-1 0401"])

In [89]:
data = data.drop(index=[80, 81])

In [90]:
data.head()

,Sequence Epitope),Binding Energy,Otsu Class theshold -77.8,Abs dist to threshold
0,RVPILRTVF,-92.5,Strong,14.7
1,VPILRTVFG,-77.1,Weak,0.7
2,RTVFGFRWL,-99.6,Strong,21.8
3,PTPPQRQAL,-48.5,Weak,29.3
4,LLSSKTSVA,-50.1,Weak,27.7

In [91]:
data.dtypes

Sequence Epitope)             object
Binding Energy               float64
Otsu Class theshold -77.8     object
Abs dist to threshold        float64
dtype: object

In [92]:
print(data.columns.tolist())

['Sequence Epitope)', 'Binding Energy ', 'Otsu Class theshold -77.8', 'Abs dist to threshold']

In [93]:
data["Sequence Epitope)"] = data["Sequence Epitope)"].astype("string")

In [94]:
data["Otsu Class theshold -77.8"] = data["Otsu Class theshold -77.8"].map({
    "Strong": 1,
    "Weak": 0
}).astype(int)

In [95]:
data.dtypes

Sequence Epitope)            string[python]
Binding Energy                      float64
Otsu Class theshold -77.8             int64
Abs dist to threshold               float64
dtype: object

In [96]:
data.head()

,Sequence Epitope),Binding Energy,Otsu Class theshold -77.8,Abs dist to threshold
0,RVPILRTVF,-92.5,1,14.7
1,VPILRTVFG,-77.1,0,0.7
2,RTVFGFRWL,-99.6,1,21.8
3,PTPPQRQAL,-48.5,0,29.3
4,LLSSKTSVA,-50.1,0,27.7

In [97]:

for i in range(9): 
    data[f"a_{i+1}"] = data["Sequence Epitope)"].str[i]

In [98]:
data = data.drop(columns=["Sequence Epitope)"])

In [99]:
data.head()

,Binding Energy,Otsu Class theshold -77.8,Abs dist to threshold,a_1,a_2,a_3,a_4,a_5,a_6,a_7,a_8,a_9
0,-92.5,1,14.7,R,V,P,I,L,R,T,V,F
1,-77.1,0,0.7,V,P,I,L,R,T,V,F,G
2,-99.6,1,21.8,R,T,V,F,G,F,R,W,L
3,-48.5,0,29.3,P,T,P,P,Q,R,Q,A,L
4,-50.1,0,27.7,L,L,S,S,K,T,S,V,A

In [100]:
# Map
map_aminoacids = {
    "A": 0,
    "R": 1,
    "N": 2,
    "D": 3,
    "E": 4,
    "Q": 5,
    "G": 6,
    "C": 7,
    "H": 8,
    "I": 9,
    "L": 10,
    "K": 11,
    "M": 12,
    "F": 13,
    "P": 14,
    "S": 15,
    "W": 16,
    "Y": 17,
    "V": 18,
    "B": 19,
    "T": 20,
}



data["a_1"] = data["a_1"].map(map_aminoacids)

data["a_2"] = data["a_2"].map(map_aminoacids)

data["a_3"] = data["a_3"].map(map_aminoacids)

data["a_4"] = data["a_4"].map(map_aminoacids)

data["a_5"] = data["a_5"].map(map_aminoacids)

data["a_6"] = data["a_6"].map(map_aminoacids)

data["a_7"] = data["a_7"].map(map_aminoacids)

data["a_8"] = data["a_8"].map(map_aminoacids)

data["a_9"] = data["a_9"].map(map_aminoacids)

In [101]:
data.head()

,Binding Energy,Otsu Class theshold -77.8,Abs dist to threshold,a_1,a_2,a_3,a_4,a_5,a_6,a_7,a_8,a_9
0,-92.5,1,14.7,1,18,14,9,10,1,20,18,13
1,-77.1,0,0.7,18,14,9,10,1,20,18,13,6
2,-99.6,1,21.8,1,20,18,13,6,13,1,16,10
3,-48.5,0,29.3,14,20,14,14,5,1,5,0,10
4,-50.1,0,27.7,10,10,15,15,11,20,15,18,0

In [102]:
sorted(data["a_5"].unique())

[np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(17),
 np.int64(18),
 np.int64(20)]

In [103]:
print(data.to_string())

    Binding Energy   Otsu Class theshold -77.8  Abs dist to threshold  a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9
0             -92.5                          1                   14.7    1   18   14    9   10    1   20   18   13
1             -77.1                          0                    0.7   18   14    9   10    1   20   18   13    6
2             -99.6                          1                   21.8    1   20   18   13    6   13    1   16   10
3             -48.5                          0                   29.3   14   20   14   14    5    1    5    0   10
4             -50.1                          0                   27.7   10   10   15   15   11   20   15   18    0
5             -72.0                          0                    5.8   15   15   11   20   15   18    0   10    6
6             -55.2                          0                   22.6   18    0   10    6    9    0   20    1   14
7             -74.0                          0                    3.8    0   20    1   14   10    1    1   13    0
8             -81.4                          1                    3.6    1   13    0   11   15   10   15    0   18
9             -65.9                          0                   11.9   15   18    1   18   13    5   20   10    1
10            -52.7                          0                   25.1   14   20   14   14    0    5    5   18   14
11            -59.1                          0                   18.7   14   14    0    5    5   18   14   10   15
12            -61.3                          0                   16.5   15   15   11   20   15    0   18   10    6
13            -93.6                          1                   15.8   14   20    5    8   20   18    1   10    9
14            -81.7                          1                    3.9    1   13    0   11   15   10    2    0    0
15            -62.7                          0                   15.1    6   20   14   18   17   18   20    9   20
16            -85.6                          1                    7.8   12   15    4   11    6   13   11   18   18
17            -81.7                          1                    3.9    4   11    6   13   11   18   18   13    6
18            -63.3                          0                   14.5   18   13    6    2   18   15    6    9   18
19            -77.8                          1                    0.0   18   18    3    8   18    1   10   10    8
20            -87.1                          1                    9.3   18    3    8   18    1   10   10    8   13
21           -103.0                          1                   25.2    8   18    1   10   10    8   13   12   20
22            -97.5                          1                   19.7    8   13   12   20   14    4   20   12    1
23            -75.8                          0                    2.0   12   20   14    4   20   12    1   16    0
24            -82.3                          1                    4.5   20   12    1   16    0   20   18   10    0
25            -67.0                          0                   10.8   10    9    3   10   11    1   18   18   10
26            -73.8                          0                    4.0    9    3   10   11    1   18   18   10    3
27            -58.3                          0                   19.5    0    0   20   14   18   20   11    9   15
28            -70.6                          0                    7.2   20   11    9   15    0    4    5   16    6
29            -72.7                          0                    5.1   18    4   18    4    6    8   10    9    3
30            -57.7                          0                   20.1   18    0   20   14    9   20    1   18   15
31            -79.3                          1                    1.5   20    1   18   15    0    4    5   16    6
32            -97.0                          1                   19.2    2    3    2    8    0   13   18   18    1
33            -60.0                          0                   17.8   10   18   14    6   10   11   15   10   18
34            -69.7                          0                    8.1   14    6   10   11   15   10   18   10    6
35            -60.3                          0                   17.5   18   11    5    6   18   18    2   10   18
36            -69.0                          0                    8.8    1    1   14    6   15   20   20   18    2
37            -71.0                          0                    6.8   10   18   14    6   13   11   15   10   18
38            -83.5                          1                    5.7   14    6   13   11   15   10   18   10    6
39            -66.8                          0                   11.0   18   11    1    6   18   18    2   10   18
40            -56.5                          0                   21.3    6   18   18    2   10   18   11   17    0
41           -101.2                          1                   23.4    4   13   15   10   14   20    8    8   20
42            -79.9                          1                    2.1   15   10   14   20    8    8   20   18    1
43            -84.8                          1                    7.0   10   14   20    8    8   20   18    1   10
44            -95.9                          1                   18.1   14   20    8    8   20   18    1   10    9
45            -79.9                          1                    2.1    4   13   15   10   14   20    5    8   20
46            -77.1                          0                    0.7   15   10   14   20    5    8   20   18    1
47            -83.2                          1                    5.4    4   15   14   20   12   14    2   17    8
48            -73.3                          0                    4.5   20    3   14   11   11   20    0    9   20
49            -72.3                          0                    5.5    0    9   20    3   15   14   15   13   10
50            -81.7                          1                    3.9    0   15    2   18   15    4   17   17    0
51            -94.4                          1                   16.6   15   13   14    6   20   14   13   13   12
52           -104.5                          1                   26.7    5    8    7   14   18   20    9   16    7
53            -72.6                          0                    5.2   14   17   11   14   14    1   20   18    9
54            -75.6                          0                    2.2    1   17    5   20    1    1    6   10   18
55            -73.3                          0                    4.5   15    2   18   10    1   15    1   13    9
56            -75.4                          0                    2.4   18    5    3    6    3   18    9   17   20
57            -85.6                          1                    7.8   17   20   14   20    8    5   20   12   10
58            -83.4                          1                    5.6    9    4    0    4   20    7   11   17   10
59            -88.4                          1                   10.6    4    0    4   20    7   11   17   10    0
60            -89.2                          1                   11.4    1   10   14   12   10    8    2   10    1
61            -94.5                          1                   16.7    8   13    4   15   20    2    1   18    0
62            -52.0                          0                   25.8    4   15   20    2    1   18    0   10   20
63            -58.0                          0                   19.8   20    2    1   18    0   10   20   12    6
64            -72.0                          0                    5.8    6    1   10   10    6   10   10    8   10
65            -80.7                          1                    2.9    1   10   10    6   10   10    8   10   10
66            -68.8                          0                    9.0   10   10    6   10   10    8   10   10    9
67            -86.9                          1                    9.1   13   10    2    7    0   13   20   13    6
68           -108.5                          1                   30.7   13   20   13    6   17   12   20   13   18
69            -77.7                          0                    0.1    8   13    5   15   20    2   11   18    0
70            -58.2                          0                   19.6    5   15   20    2   11   18    0   10   20
71            -61.6                          0                   16.2   20    2   11   18    0   10   20   12    6
72            -68.8                          0                    9.0   20   12    6    0   18   18    0   10   10
73            -76.0                          0                    1.8    6    0   18   18    0   10   10   16    6
74            -94.3                          1                   16.5   11    2   14    4   11   14    8   13   14
75            -83.1                          1                    5.3   14    4   11   14    8   13   14   10    0
76            -96.8                          1                   19.0    4    3    3   18    1    8    8   13   20
77            -83.7                          1                    5.9   11    2   14    6   11   14    8   13   14
78            -89.4                          1                   11.6   14    6   11   14    8   13   14   10    0
79            -98.2                          1                   20.4    4    3    3   18    1    8   14   13   20

In [104]:
data_true = pd.get_dummies(data,columns=["a_1","a_2","a_3","a_4","a_5","a_6","a_7","a_8","a_9"]).astype(int)

In [105]:
data_true = data_true.drop(columns=["Abs dist to threshold"])

In [106]:
data_true.head()

,Binding Energy,Otsu Class theshold -77.8,a_1_0,a_1_1,a_1_2,a_1_4,a_1_5,a_1_6,a_1_8,a_1_9,...,a_9_7,a_9_8,a_9_9,a_9_10,a_9_12,a_9_13,a_9_14,a_9_15,a_9_18,a_9_20
0,-92,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,-77,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-99,1,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,-48,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,-50,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [107]:
print(data_true.to_string())

    Binding Energy   Otsu Class theshold -77.8  a_1_0  a_1_1  a_1_2  a_1_4  a_1_5  a_1_6  a_1_8  a_1_9  a_1_10  a_1_11  a_1_12  a_1_13  a_1_14  a_1_15  a_1_17  a_1_18  a_1_20  a_2_0  a_2_1  a_2_2  a_2_3  a_2_4  a_2_5  a_2_6  a_2_8  a_2_9  a_2_10  a_2_11  a_2_12  a_2_13  a_2_14  a_2_15  a_2_17  a_2_18  a_2_20  a_3_0  a_3_1  a_3_2  a_3_3  a_3_4  a_3_5  a_3_6  a_3_7  a_3_8  a_3_9  a_3_10  a_3_11  a_3_12  a_3_13  a_3_14  a_3_15  a_3_18  a_3_20  a_4_0  a_4_2  a_4_3  a_4_4  a_4_5  a_4_6  a_4_7  a_4_8  a_4_9  a_4_10  a_4_11  a_4_12  a_4_13  a_4_14  a_4_15  a_4_16  a_4_18  a_4_20  a_5_0  a_5_1  a_5_3  a_5_5  a_5_6  a_5_7  a_5_8  a_5_9  a_5_10  a_5_11  a_5_12  a_5_13  a_5_14  a_5_15  a_5_17  a_5_18  a_5_20  a_6_0  a_6_1  a_6_2  a_6_4  a_6_5  a_6_7  a_6_8  a_6_10  a_6_11  a_6_12  a_6_13  a_6_14  a_6_15  a_6_18  a_6_20  a_7_0  a_7_1  a_7_2  a_7_5  a_7_6  a_7_8  a_7_9  a_7_10  a_7_11  a_7_13  a_7_14  a_7_15  a_7_17  a_7_18  a_7_20  a_8_0  a_8_1  a_8_8  a_8_9  a_8_10  a_8_12  a_8_13  a_8_16  a_8_17  a_8_18  a_9_0  a_9_1  a_9_2  a_9_3  a_9_6  a_9_7  a_9_8  a_9_9  a_9_10  a_9_12  a_9_13  a_9_14  a_9_15  a_9_18  a_9_20
0               -92                          1      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      1       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      0      0      0       0       0       0       0       0       1      0      0      0      0      0      0      0      0       0       0       1       0       0       0       0
1               -77                          0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0      0      1       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0       0      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      0      0      0       0       0       1       0       0       0      0      0      0      0      1      0      0      0       0       0       0       0       0       0       0
2               -99                          1      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0       0      0      0      0      0      1      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0       0       0       0       1       0       0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0
3               -48                          0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      1      0      0      0      0       0       0       0       0       0       0       0       0       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      1      0      0      0       0       0       0       0       0       0       0       0      1      0      0      0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0
4               -50                          0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0       0       1       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      0      0      0      0       0       0       0       0       0       1      1      0      0      0      0      0      0      0       0       0       0       0       0       0       0
5               -72                          0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0      0       0       1       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0       1       0       0       0       0       0      0      0      0      0      1      0      0      0       0       0       0       0       0       0       0
6               -55                          0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      1      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0      0      0      0      0      0      1      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      1       0       0       0       0       0       0       0       0       0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      1      0      0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0
7               -74                          0      1      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      1      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0       0       0       1       0       0       0      1      0      0      0      0      0      0      0       0       0       0       0       0       0       0
8               -81                          1      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0       0      1      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       1       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      1      0      0      0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0
9               -65                          0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      0      1      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0       0      0      0      0      0      1      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      0      0      0       1       0       0       0       0       0      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0
10              -52                          0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      1      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      1      0      0       0       0       0       0       0       0       0       0      0      0      0      1      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0       0       0       0       0       0       1      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0
11              -59                          0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      1      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      1      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      1      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0      0      0      0      0       1       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0
12              -61                          0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0      0       0       1       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      0      0      0       1       0       0       0       0       0      0      0      0      0      1      0      0      0       0       0       0       0       0       0       0
13              -93                          1      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      1      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      1      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      1      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0       1       0       0       0       0       0      0      0      0      0      0      0      0      1       0       0       0       0       0       0       0
14              -81                          1      0      1      0      0      0      0      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       1       0       0       0       0       0      1      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       1       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0       1       0       0       0       0       0       0       0      0      0      1      0      0      0      0       0       0       0       0       0       0       0       0      1      0      0      0       0       0       0       0       0       0      1      0      0      0      0      0      0      0       0       0       0       0       0       0       0
15              -62                          0      0      0      0      0      0      1      0      0       0       0       0       0       0       0       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       0       1      0      0      0      0      0      0      0      0      0      0       0       0       0       0       1       0       0       0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0       0      0      0      0      0      0      0      0       0       0       0       0       0       0       1       0      0      0      0      0      0      0      0       0       0       0       0       0       0       0       1      0      0      0      1       0       0       0       0       0       0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       1

In [108]:
import numpy as np
from cvxopt import matrix, solvers

from sklearn.base import BaseEstimator, ClassifierMixin
class SVM(BaseEstimator, ClassifierMixin):
    """
    Support Vector Machine (SVM) classifier implemented using
    quadratic programming.

    This class supports linear, polynomial, radial basis function (RBF),
    and custom precomputed kernels. It follows the scikit-learn estimator
    interface, allowing compatibility with standard ML workflows.

    Parameters
    ----------
    C : float, default=10
        Regularization parameter that controls the trade-off between
        maximizing the margin and minimizing classification error.

    kernel : str, default='poly'
        Kernel type to be used in the algorithm. Options are:
        'linear', 'poly', 'rbf', or 'Given'.

    r : float, default=1
        Independent term in the polynomial kernel.

    d : int, default=3
        Degree of the polynomial kernel.

    gamma : float, default=0.1
        Kernel coefficient for the RBF kernel.

    k_given : array-like, optional
        Precomputed kernel matrix used when kernel='Given'.

    Attributes
    ----------
    alpha : ndarray
        Lagrange multipliers obtained from the quadratic optimization.

    support_vectors : ndarray
        Subset of training data corresponding to non-zero alpha values.

    w : ndarray or None
        Weight vector (only for linear kernel).

    b : float
        Bias term of the decision function.

    Notes
    -----
    This implementation solves the dual optimization problem using
    quadratic programming via cvxopt.
    """
    def __init__(self, C=10, kernel='poly', r=1, d=3, gamma=0.1,k_given = None):
        self.C = C
        self.kernel = kernel
        self.r = r
        self.d = d
        self.gamma = gamma
        self.alpha = None
        self.support_vectors = None
        self.w = None
        self.b = None
        self.k_given = k_given
    
    def get_params(self, deep=True):
        return {
            'C': self.C,
            'kernel': self.kernel,
            'r': self.r,
            'd': self.d,
            'gamma': self.gamma
        }
    
    def set_params(self, **parameters):
        for parameter, value in parameters.items():
            setattr(self, parameter, value)
        return self
    
    def polynomial_kernel(self, X1, X2):
        return (np.dot(X1, X2.T) + self.r) ** self.d
    
    def rbf_kernel(self, X1, X2):
        sq_dist = np.sum(X1**2, axis=1).reshape(-1, 1) + np.sum(X2**2, axis=1) - 2 * np.dot(X1, X2.T)
        return np.exp(-self.gamma * np.clip(sq_dist, 0, None))
    
    def fit(self, X, y):
        m, n = X.shape
        y = np.where(y <= 0, -1, 1)

        if self.kernel == 'linear':
            K = np.dot(X, X.T)
        elif self.kernel == 'poly':
            K = self.polynomial_kernel(X,X)
        elif self.kernel == 'rbf':
            K = self.rbf_kernel(X, X)
        elif self.kernel == 'Given':
            K= self.k_given
        else:
            raise ValueError("Kernel no soportado")

        P = np.outer(y, y) * K
        P = matrix(P.astype(np.double))
        q = matrix(-np.ones(m).astype(np.double))
        G = matrix(np.vstack((-np.eye(m), np.eye(m))))
        h = matrix(np.hstack((np.zeros(m), np.ones(m) * self.C)))
        A = matrix(y.reshape(1, -1).astype(np.double))
        b = matrix(0.0)

        sol = solvers.qp(P, q, G, h, A, b)
        self.alpha = np.array(sol['x']).flatten()
        sv_indices = self.alpha > 1e-5
        self.support_vectors = X[sv_indices]
        self.alpha_sv = self.alpha[sv_indices]
        self.y_sv = y[sv_indices]
        
        if self.kernel == 'linear':
            self.w = np.sum((self.alpha_sv * self.y_sv).reshape(-1, 1) * self.support_vectors, axis=0)
        else:
            self.w = None
        
        self.b = np.mean(self.y_sv - np.dot(self.support_vectors, self.w)) if self.kernel == 'linear' else np.mean(self.y_sv)
    
    def predict(self, X):
        if self.kernel == 'linear':
            output = np.dot(X, self.w) + self.b
        elif self.kernel == 'poly':
            output = np.sum(
                (self.alpha_sv * self.y_sv).reshape(-1, 1) * 
                (np.dot(self.support_vectors, X.T) + self.r) ** self.d,
                axis=0
            ) + self.b
        elif self.kernel == 'rbf':
            output = np.sum(
                (self.alpha_sv * self.y_sv).reshape(-1, 1) * 
                self.rbf_kernel(self.support_vectors, X),
                axis=0
            ) + self.b
        return np.where(output >= 0, 1, 0)

In [109]:
import numpy as np
import pandas as pd
import cvxopt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split , KFold
from sklearn.metrics import accuracy_score

In [110]:
from sklearn.model_selection import ShuffleSplit
import pandas as pd

X = data.drop(columns=['Otsu Class theshold -77.8'])
y = data['Otsu Class theshold -77.8']

ss = ShuffleSplit(n_splits=4, test_size=0.5, random_state=19)

folds_data = []

for fold, (train_idx, val_idx) in enumerate(ss.split(X, y)):
    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_val = X.iloc[val_idx]
    y_val = y.iloc[val_idx]

    folds_data.append({
        'fold': fold + 1,
        'X_train': X_train,
        'y_train': y_train,
        'X_val': X_val,
        'y_val': y_val
    })

In [111]:
# from sklearn.model_selection import ShuffleSplit
# import pandas as pd

# X = data.drop(columns=['Otsu Class theshold -77.8'])
# y = data['Otsu Class theshold -77.8']

# ss = ShuffleSplit(n_splits=4, test_size=0.91, random_state=42)
# from sklearn.decomposition import PCA
# from qiskit.circuit.library import ZZFeatureMap
# import seaborn as sns
# import matplotlib.pyplot as plt
# from sklearn.preprocessing import MinMaxScaler

# # 1. Reducción de Dimensionalidad con PCA
# # Reducimos de 10 features a 4 features (para usar solo 4 qubits)
# n_qubits_reduced = 4  
# pca = PCA(n_components=n_qubits_reduced)

# # Ajustamos PCA con TODOS los datos de entrenamiento disponibles (uniendo folds o el set principal)
# # Asumiendo que 'X' es tu dataframe original antes de dividirlo en folds
# X_pca = pca.fit_transform(X)

# # Escalamos de nuevo a (0, 2pi) o (-pi, pi) DESPUES de PCA
# scaler_pca = MinMaxScaler(feature_range=(0, 2*np.pi))
# X_pca_scaled = scaler_pca.fit_transform(X_pca)
# folds_data = []
# n_folds = 4
# for fold in range(n_folds):

#     X_tr, X_v, y_tr, y_v = train_test_split(
#         X_pca_scaled, y, test_size=0.9, shuffle=True, random_state=19 + fold
#     )
#     folds_data.append({
#         'fold': fold + 1,
#         'X_train': X_tr,
#         'y_train': y_tr,
#         'X_val': X_v,
#         'y_val': y_v
#     })

In [112]:

# Fold 1
fold_1_X_train = folds_data[0]['X_train']
fold_1_y_train = folds_data[0]['y_train']
fold_1_X_val = folds_data[0]['X_val']
fold_1_y_val = folds_data[0]['y_val']
# fold 2
fold_2_X_train = folds_data[1]['X_train']
fold_2_y_train = folds_data[1]['y_train']
fold_2_X_val = folds_data[1]['X_val']
fold_2_y_val = folds_data[1]['y_val']
# fold 3
fold_3_X_train = folds_data[2]['X_train']
fold_3_y_train = folds_data[2]['y_train']
fold_3_X_val = folds_data[2]['X_val']
fold_3_y_val = folds_data[2]['y_val']
# fold 4
fold_4_X_train = folds_data[3]['X_train']
fold_4_y_train = folds_data[3]['y_train']
fold_4_X_val = folds_data[3]['X_val']
fold_4_y_val = folds_data[3]['y_val']

In [113]:
len(fold_1_X_val)

40

In [114]:
scaler = StandardScaler()

#standarize data for training
scaler.fit(fold_1_X_train)
scaler.fit(fold_2_X_train)
scaler.fit(fold_3_X_train)
scaler.fit(fold_4_X_train)

# standarize data for validation
scaler.fit(fold_1_X_val)
scaler.fit(fold_2_X_val)
scaler.fit(fold_3_X_val)
scaler.fit(fold_4_X_val)

StandardScaler()

In [115]:
# standarize variable for training
standar_fold_1_X_train = scaler.transform(fold_1_X_train)
standar_fold_2_X_train = scaler.transform(fold_2_X_train)
standar_fold_3_X_train = scaler.transform(fold_3_X_train)
standar_fold_4_X_train = scaler.transform(fold_4_X_train)
# standarize variable for vaidation
standar_fold_1_X_val = scaler.transform(fold_1_X_val)
standar_fold_2_X_val = scaler.transform(fold_2_X_val)
standar_fold_3_X_val = scaler.transform(fold_3_X_val)
standar_fold_4_X_val = scaler.transform(fold_4_X_val)

In [116]:
print(len(standar_fold_1_X_train))

40

In [117]:
print(len(standar_fold_1_X_val))

40

In [118]:
# classifier = SVM(C = 1 ,kernel = 'rbf', r = 0.2 , d = 2, gamma = 0.1,k_given= None) # best fo 50%

In [119]:
classifier = SVM(C = 1 ,kernel = 'linear', r = 0.2 , d = 2, gamma = 0.01,k_given= None) # best fo 50% linear

In [120]:
# clasifier for fold 1 with C = 1
classifier.fit(standar_fold_1_X_train , fold_1_y_train)

     pcost       dcost       gap    pres   dres
 0: -1.0523e+01 -7.9699e+01  4e+02  2e+00  2e-15
 1: -6.2205e+00 -4.7708e+01  7e+01  3e-01  1e-15
 2: -3.5818e+00 -1.1216e+01  8e+00  2e-02  4e-15
 3: -4.8868e+00 -6.4492e+00  2e+00  3e-03  2e-15
 4: -5.3213e+00 -5.8004e+00  5e-01  6e-04  2e-15
 5: -5.4922e+00 -5.5742e+00  8e-02  7e-05  2e-15
 6: -5.5194e+00 -5.5330e+00  1e-02  1e-05  1e-15
 7: -5.5246e+00 -5.5249e+00  3e-04  1e-07  2e-15
 8: -5.5247e+00 -5.5247e+00  4e-06  1e-09  2e-15
Optimal solution found.

In [121]:
# accuracy score on the training data (Ein)
X_train_prediction = classifier.predict(standar_fold_1_X_train)
training_data_accuracy = accuracy_score( fold_1_y_train, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy)

Accuracy score of the test data :  0.975

In [122]:
# accuracy score on the validating data (Eout)
X_train_prediction = classifier.predict(standar_fold_1_X_val)
training_data_accuracy_1 = accuracy_score( fold_1_y_val, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy_1)

Accuracy score of the test data :  0.9

In [123]:
# clasifier for fold 2 with C = 1
classifier.fit(standar_fold_2_X_train , fold_2_y_train)

     pcost       dcost       gap    pres   dres
 0: -1.0859e+01 -7.2692e+01  3e+02  2e+00  3e-15
 1: -6.8857e+00 -4.1798e+01  5e+01  2e-01  2e-15
 2: -5.1438e+00 -1.2518e+01  9e+00  2e-02  3e-15
 3: -6.1695e+00 -7.6583e+00  2e+00  4e-03  2e-15
 4: -6.5954e+00 -6.8440e+00  3e-01  6e-04  1e-15
 5: -6.6761e+00 -6.7085e+00  3e-02  5e-05  2e-15
 6: -6.6867e+00 -6.6881e+00  1e-03  2e-06  2e-15
 7: -6.6871e+00 -6.6872e+00  2e-05  2e-08  2e-15
 8: -6.6872e+00 -6.6872e+00  2e-07  2e-10  3e-15
Optimal solution found.

In [124]:
# accuracy score on the training data (Ein)
X_train_prediction = classifier.predict(standar_fold_2_X_train)
training_data_accuracy = accuracy_score( fold_2_y_train, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy)

Accuracy score of the test data :  0.95

In [125]:
# accuracy score on the validating data (Eout)
X_train_prediction = classifier.predict(standar_fold_2_X_val)
training_data_accuracy_2 = accuracy_score( fold_2_y_val, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy_2)

Accuracy score of the test data :  0.875

In [126]:
# clasifier for fold 3 with C = 1
classifier.fit(standar_fold_3_X_train , fold_3_y_train)

     pcost       dcost       gap    pres   dres
 0: -9.9859e+00 -7.4994e+01  3e+02  2e+00  2e-15
 1: -5.9078e+00 -4.2833e+01  6e+01  3e-01  3e-15
 2: -3.8489e+00 -9.8913e+00  7e+00  2e-02  9e-15
 3: -4.9386e+00 -6.0900e+00  1e+00  3e-03  3e-15
 4: -5.2754e+00 -5.4452e+00  2e-01  3e-04  3e-15
 5: -5.3392e+00 -5.3467e+00  8e-03  9e-06  2e-15
 6: -5.3426e+00 -5.3428e+00  2e-04  2e-07  3e-15
 7: -5.3427e+00 -5.3427e+00  3e-06  2e-09  3e-15
Optimal solution found.

In [127]:
# accuracy score on the training data (Ein)
X_train_prediction = classifier.predict(standar_fold_3_X_train)
training_data_accuracy = accuracy_score( fold_3_y_train, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy)

Accuracy score of the test data :  0.975

In [128]:
# accuracy score on the validating data (Eout)
X_train_prediction = classifier.predict(standar_fold_3_X_val)
training_data_accuracy_3 = accuracy_score( fold_3_y_val, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy_3)

Accuracy score of the test data :  0.9

In [129]:
# clasifier for fold 3 with C = 1
classifier.fit(standar_fold_4_X_train , fold_4_y_train)

     pcost       dcost       gap    pres   dres
 0: -1.2119e+01 -8.3774e+01  4e+02  2e+00  3e-15
 1: -7.4956e+00 -5.2081e+01  7e+01  3e-01  2e-15
 2: -6.0499e+00 -1.3950e+01  9e+00  2e-02  6e-15
 3: -7.2746e+00 -8.7571e+00  2e+00  3e-03  4e-15
 4: -7.6832e+00 -8.2670e+00  6e-01  7e-04  2e-15
 5: -7.8106e+00 -7.9605e+00  2e-01  2e-05  2e-15
 6: -7.8622e+00 -7.8710e+00  9e-03  1e-06  3e-15
 7: -7.8653e+00 -7.8655e+00  1e-04  2e-08  2e-15
 8: -7.8654e+00 -7.8654e+00  1e-06  2e-10  3e-15
Optimal solution found.

In [130]:
# accuracy score on the training data (Ein)
X_train_prediction = classifier.predict(standar_fold_4_X_train)
training_data_accuracy = accuracy_score( fold_4_y_train, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy)

Accuracy score of the test data :  0.975

In [131]:
# accuracy score on the validating data (Eout)
X_train_prediction = classifier.predict(standar_fold_4_X_val)
training_data_accuracy_4 = accuracy_score( fold_4_y_val, X_train_prediction)
print('Accuracy score of the test data : ', training_data_accuracy_4)

Accuracy score of the test data :  0.975

In [132]:
CV = training_data_accuracy_4 + training_data_accuracy_3 + training_data_accuracy_2 + training_data_accuracy_1
print("Acording to the cross validation the expected Eout without kernel is == " , 1- CV/4 )
print("So the Accuracy score is == " , CV/4)
val = CV/4*100
valpercent = format(val, ".4g")
print("So we get a" , valpercent, "% Accuracy") # for 20% it is very accurate!

Acording to the cross validation the expected Eout without kernel is ==  0.08750000000000002
So the Accuracy score is ==  0.9125
So we get a 91.25 % Accuracy

In [133]:
# classifier = SVM(C = 1 ,kernel = 'rbf', r = 0.2 , d = 2, gamma = 0.03,k_given= None) # this one showed the best results for 20% training

In [134]:
# classifier = SVM(C = 0.1 ,kernel = 'linear', r = 0.2 , d = 2, gamma = 0.04,k_given= None) # this one showed the best results for 10% training

In [135]:
# classifier = SVM(C = 0.001,kernel = 'rbf', r = 0.2 , d = 2, gamma = 0.004,k_given= None) # this one showed the best results for 5% training

In [136]:
# classifier = SVM(C = 1 ,kernel = 'linear', r = 0.2 , d = 2, gamma = 0.01,k_given= None) # linear kernel

In [137]:
# for rbf
### 69.53% for 20% of the data
### 68.40% for 10% of the data
### 57.57% for 5% of the data

In [138]:
# linear
### 71.88% for 20% of the data
### 69.44% for 10% of the data
### 62.50% for 5% of the data